language: go
go:
  - 1.6
  - 1.5.3

sudo: false

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get -u github.com/golang/lint/golint
  - mkdir -p $GOPATH/src/github.com/vbatts && ln -sf $(pwd) $GOPATH/src/github.com/vbatts/git-validation && go get ./... && go install github.com/vbatts/git-validation

install: true

script:
  - go vet -x ./...
  - golint ./...
  - go build .
  - go test -v ./...
  - git-validation -v -run short-subject,dangling-whitespace

